DROP TABLE IF EXISTS  MULTIPLES;

CREATE TABLE  "MULTIPLES" (
	"TYPE" INTEGER IDENTITY PRIMARY KEY,
	"PE" FLOAT NOT NULL,
    "EVEBITDA" FLOAT NOT NULL,
    "EVEBIT" FLOAT NOT NULL,
    "REVENUE" FLOAT NOT NULL
);